[package]
name = "driputils"
version = "0.1.0"
description = "A library for working with Drip module format"
authors = ["Sam Harrison <epicpotatopro@gmail.com>"]

[[bin]]
name = "dripl"
path = "src/bin/dripl.rs"
